apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-service
  namespace: {{ $.Values.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.exposedPort }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ $.Release.Name }}
